--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/10/2022 5:11:33
-- Server version: 8.0.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `api.tikect`;

CREATE DATABASE IF NOT EXISTS `api.tikect`
	CHARACTER SET utf8mb3
	COLLATE utf8_general_ci;

--
-- Set default database
--
USE `api.tikect`;

--
-- Create table `tbl_ticket`
--
CREATE TABLE IF NOT EXISTS tbl_ticket (
  Id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  nameTicket LONGTEXT BINARY NOT NULL,
  numberTicket BIGINT NOT NULL AUTO_INCREMENT,
  asunto LONGTEXT BINARY NOT NULL,
  persona_solicitante LONGTEXT BINARY NOT NULL,
  descripcion_de_licencia LONGTEXT BINARY NOT NULL,
  feca_de_ingreso DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_modificado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  INDEX UX_IDTypes_numberTicket(numberTicket)
)
ENGINE = INNODB,
AUTO_INCREMENT = 212162,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb3,
COLLATE utf8_bin;

--
-- Create table `tbl_historial`
--
CREATE TABLE IF NOT EXISTS tbl_historial (
  Id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  usuario_soporte LONGTEXT BINARY NOT NULL,
  comentario_trabajo_realizado LONGTEXT BINARY NOT NULL,
  id_Ticket CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  feca_de_ingreso DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_modificado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8_bin;

--
-- Create index `IX_tbl_historial_id_Ticket` on table `tbl_historial`
--
ALTER TABLE tbl_historial 
  ADD INDEX IX_tbl_historial_id_Ticket(id_Ticket);

--
-- Create foreign key
--
ALTER TABLE tbl_historial 
  ADD CONSTRAINT FK_ticket_histrial FOREIGN KEY (id_Ticket)
    REFERENCES tbl_ticket(Id) ON DELETE CASCADE;

--
-- Create table `__efmigrationshistory`
--
CREATE TABLE IF NOT EXISTS __efmigrationshistory (
  MigrationId VARCHAR(150) NOT NULL,
  ProductVersion VARCHAR(32) NOT NULL,
  PRIMARY KEY (MigrationId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table tbl_ticket
--
BEGIN;
INSERT INTO tbl_ticket VALUES
('3490760d-2b55-4a9a-870c-2ae65509020e', 'CTE', 212161, 'miau', 'maiu', 'maiud', '2022-10-07 04:32:47', '2022-10-07 04:32:47'),
('44b6acf9-ede6-4206-a5fa-a27ac7c9be9b', 'CTE', 212158, 'miau', 'Jhonn Taylor', 'yosd', '2022-10-06 02:24:16', '2022-10-07 04:29:01'),
('5433e033-1a8a-423f-967e-e03a8281ba38', 'CTE', 212160, 'hola', 'gato', 'michu', '2022-10-07 02:56:12', '2022-10-07 02:56:12'),
('ef08aab7-f7a5-42b9-8607-6aa2ae983244', 'CTE', 212159, 'fdfdf', 'kkkmkmk', 'kmkmkkm', '2022-10-07 02:53:44', '2022-10-07 02:53:44');
COMMIT;

-- 
-- Dumping data for table __efmigrationshistory
--
BEGIN;
INSERT INTO __efmigrationshistory VALUES
('20221005192736_1', '6.0.9'),
('20221005192931_12', '6.0.9'),
('20221005192958_2', '6.0.9');
COMMIT;

-- 
-- Dumping data for table tbl_historial
--
-- Table `api.tikect`.tbl_historial does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;